#!/bin/bash
# Concatenate all compat JS files into a single bundle for embedding
# Output: compat/compat_bundle.js

set -e

DIR="$(cd "$(dirname "$0")" && pwd)"
OUT="$DIR/compat_bundle.js"

echo "// compat_bundle.js - Auto-generated by build_compat_bundle.sh" > "$OUT"
echo "// Do not edit manually. Regenerate with: bash compat/build_compat_bundle.sh" >> "$OUT"
echo "" >> "$OUT"

cat \
    "$DIR/require.js" \
    "$DIR/process.js" \
    "$DIR/node_path.js" \
    "$DIR/node_os.js" \
    "$DIR/node_events.js" \
    "$DIR/node_fs.js" \
    "$DIR/electron.js" \
    >> "$OUT"

# Register the electron module under both names at the end
cat >> "$OUT" << 'EOF'

// ---------------------------------------------------------------------------
// Register electron module
// ---------------------------------------------------------------------------
registerModule('electron', exports);
registerModule('lightshell/electron', exports);
EOF

echo "Built compat bundle: $OUT ($(wc -c < "$OUT" | tr -d ' ') bytes)"
